apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gateway-service.fullname" . }}-config
  labels:
    {{- include "gateway-service.labels" . | nindent 4 }}
data:
  KSERVE_URL: {{ .Values.configMap.kserveUrl | quote }}
